// <auto-generated />
using System;
using System.Collections.Generic;
using Iris.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Iris.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IrisDbContext))]
    [Migration("20260904093814_AddApplicationInstallations")]
    partial class AddApplicationInstallations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Iris.Domain.Access.EditLock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AcquiredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("HolderDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HolderUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RefreshedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResourceType", "ResourceId")
                        .IsUnique();

                    b.ToTable("EditLocks", (string)null);
                });

            modelBuilder.Entity("Iris.Domain.Access.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Permissions");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Iris.Domain.Access.RoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("Scope", "Iris.Domain.Access.RoleAssignment.Scope#AccessScope", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid?>("ContextId")
                                .HasColumnType("TEXT")
                                .HasColumnName("ScopeContextId");

                            b1.Property<Guid?>("CustomerId")
                                .HasColumnType("TEXT")
                                .HasColumnName("ScopeCustomerId");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("ScopeType");
                        });

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "RoleId");

                    b.ToTable("RoleAssignments", (string)null);
                });

            modelBuilder.Entity("Iris.Domain.Access.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsProvisioned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PasswordSetupPending")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("PasswordUpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Iris.Domain.Access.UserInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IssuedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserInvitations", (string)null);
                });

            modelBuilder.Entity("Iris.Domain.Access.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions", (string)null);
                });

            modelBuilder.Entity("Iris.Domain.Applications.ApplicationDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactFeed")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactName")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactProvider")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("BuildPipelineUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Applications", (string)null);
                });

            modelBuilder.Entity("Iris.Domain.Applications.ApplicationInstallation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationUnitKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationVersionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallationProfileKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerNodeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ApplicationVersionId");

                    b.HasIndex("ServerNodeId");

                    b.ToTable("ApplicationInstallations", (string)null);
                });

            modelBuilder.Entity("Iris.Domain.Applications.ApplicationInstallationBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationInstallationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceholderKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetSlug")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValuePreview")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationInstallationId");

                    b.ToTable("ApplicationInstallationBindings", (string)null);
                });

            modelBuilder.Entity("Iris.Domain.Applications.ApplicationUnitDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryPoint")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionTargetsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilesJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationVersionId");

                    b.HasIndex("ApplicationVersionId", "Key")
                        .IsUnique();

                    b.ToTable("ApplicationUnits", (string)null);
                });

            modelBuilder.Entity("Iris.Domain.Applications.ApplicationVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ImportWarnings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastImportSchemaVersion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawImportPackageJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Version")
                        .IsUnique();

                    b.ToTable("ApplicationVersions", (string)null);
                });

            modelBuilder.Entity("Iris.Domain.Applications.ConfigurationKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemSchemaJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceholderKey")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileDefaultsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Required")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolutionJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Secret")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerializationJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationVersionId");

                    b.ToTable("ApplicationConfigurationKeys", (string)null);
                });

            modelBuilder.Entity("Iris.Domain.Applications.DependencyConstraintDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceholderKey")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceKind")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionExpression")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationVersionId");

                    b.ToTable("ApplicationDependencyConstraints", (string)null);
                });

            modelBuilder.Entity("Iris.Domain.Applications.DependencyDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceholderKey")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderApplicationSlug")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderPlaceholderKey")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Required")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationVersionId");

                    b.ToTable("ApplicationDependencies", (string)null);
                });

            modelBuilder.Entity("Iris.Domain.Applications.InstallationProfileDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationKeysJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Multiple")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Required")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationVersionId");

                    b.HasIndex("ApplicationVersionId", "Key")
                        .IsUnique();

                    b.ToTable("ApplicationInstallationProfiles", (string)null);
                });

            modelBuilder.Entity("Iris.Domain.Applications.PlaceholderDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Required")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationVersionId");

                    b.ToTable("ApplicationPlaceholders", (string)null);
                });

            modelBuilder.Entity("Iris.Domain.Audit.TransactionLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.HasIndex("ActorUserId", "OccurredAtUtc");

                    b.HasIndex("Area", "OccurredAtUtc");

                    b.ToTable("TransactionLog", (string)null);
                });

            modelBuilder.Entity("Iris.Domain.Infrastructure.DataServiceInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSecretReference")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StorageGb")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataServices", (string)null);
                });

            modelBuilder.Entity("Iris.Domain.Infrastructure.ServerCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretReference")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerNodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("ServerNodeId", "Username")
                        .IsUnique();

                    b.ToTable("ServerCredentials", (string)null);
                });

            modelBuilder.Entity("Iris.Domain.Infrastructure.ServerNode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Capabilities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("HostingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MachineSize")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Os")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrivateIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("UsedPorts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Servers", (string)null);
                });

            modelBuilder.Entity("Iris.Domain.Settings.MailProviderSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableSsl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("FromDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpHost")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpPasswordSecretReference")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpUsername")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MailProviderSettings", (string)null);
                });

            modelBuilder.Entity("Iris.Domain.Tenancy.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("Iris.Domain.Tenancy.CustomerContext", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "Name")
                        .IsUnique();

                    b.ToTable("CustomerContexts", (string)null);
                });

            modelBuilder.Entity("Iris.Domain.Access.RoleAssignment", b =>
                {
                    b.HasOne("Iris.Domain.Access.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Iris.Domain.Access.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Iris.Domain.Access.UserInvitation", b =>
                {
                    b.HasOne("Iris.Domain.Access.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Iris.Domain.Access.UserSession", b =>
                {
                    b.HasOne("Iris.Domain.Access.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Iris.Domain.Applications.ApplicationInstallationBinding", b =>
                {
                    b.HasOne("Iris.Domain.Applications.ApplicationInstallation", null)
                        .WithMany("Bindings")
                        .HasForeignKey("ApplicationInstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Iris.Domain.Applications.ApplicationUnitDefinition", b =>
                {
                    b.HasOne("Iris.Domain.Applications.ApplicationVersion", null)
                        .WithMany("ApplicationUnits")
                        .HasForeignKey("ApplicationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Iris.Domain.Applications.ApplicationVersion", b =>
                {
                    b.HasOne("Iris.Domain.Applications.ApplicationDefinition", null)
                        .WithMany("Versions")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Iris.Domain.Applications.RuntimeMetadata", "RuntimeMetadata", b1 =>
                        {
                            b1.Property<Guid>("ApplicationVersionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ExecutionTargetsJson")
                                .HasColumnType("TEXT")
                                .HasColumnName("ExecutionTargetsJson");

                            b1.Property<int?>("MinimumCpuCores")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MinimumCpuCores");

                            b1.Property<int?>("MinimumMemoryMb")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MinimumMemoryMb");

                            b1.Property<string>("OsSupportJson")
                                .HasColumnType("TEXT")
                                .HasColumnName("OsSupportJson");

                            b1.Property<string>("PortKeysJson")
                                .HasColumnType("TEXT")
                                .HasColumnName("PortKeysJson");

                            b1.Property<string>("PreferredOs")
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("PreferredOs");

                            b1.Property<int?>("RequiredCpuCores")
                                .HasColumnType("INTEGER")
                                .HasColumnName("RequiredCpuCores");

                            b1.Property<int?>("RequiredMemoryMb")
                                .HasColumnType("INTEGER")
                                .HasColumnName("RequiredMemoryMb");

                            b1.PrimitiveCollection<string>("RequiredPorts")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("RequiredPorts");

                            b1.Property<string>("RuntimeName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("RuntimeName");

                            b1.HasKey("ApplicationVersionId");

                            b1.ToTable("ApplicationVersions");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationVersionId");
                        });

                    b.Navigation("RuntimeMetadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Iris.Domain.Applications.ConfigurationKey", b =>
                {
                    b.HasOne("Iris.Domain.Applications.ApplicationVersion", null)
                        .WithMany("ConfigurationKeys")
                        .HasForeignKey("ApplicationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Iris.Domain.Applications.DependencyConstraintDefinition", b =>
                {
                    b.HasOne("Iris.Domain.Applications.ApplicationVersion", null)
                        .WithMany("DependencyConstraints")
                        .HasForeignKey("ApplicationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Iris.Domain.Applications.DependencyDefinition", b =>
                {
                    b.HasOne("Iris.Domain.Applications.ApplicationVersion", null)
                        .WithMany("Dependencies")
                        .HasForeignKey("ApplicationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Iris.Domain.Applications.InstallationProfileDefinition", b =>
                {
                    b.HasOne("Iris.Domain.Applications.ApplicationVersion", null)
                        .WithMany("InstallationProfiles")
                        .HasForeignKey("ApplicationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Iris.Domain.Applications.PlaceholderDefinition", b =>
                {
                    b.HasOne("Iris.Domain.Applications.ApplicationVersion", null)
                        .WithMany("Placeholders")
                        .HasForeignKey("ApplicationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Iris.Domain.Infrastructure.ServerCredential", b =>
                {
                    b.HasOne("Iris.Domain.Infrastructure.ServerNode", null)
                        .WithMany("Credentials")
                        .HasForeignKey("ServerNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Iris.Domain.Infrastructure.ServerNode", b =>
                {
                    b.OwnsOne("Iris.Domain.Infrastructure.ResourceProfile", "Resources", b1 =>
                        {
                            b1.Property<Guid>("ServerNodeId")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ApplicationDiskGb")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ResourceApplicationDiskGb");

                            b1.Property<int?>("BackupDiskGb")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ResourceBackupDiskGb");

                            b1.Property<int?>("CpuCores")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ResourceCpuCores");

                            b1.Property<int?>("DiskGb")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ResourceDiskGb");

                            b1.Property<int?>("MemoryMb")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ResourceMemoryMb");

                            b1.HasKey("ServerNodeId");

                            b1.ToTable("Servers");

                            b1.WithOwner()
                                .HasForeignKey("ServerNodeId");
                        });

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("Iris.Domain.Tenancy.CustomerContext", b =>
                {
                    b.HasOne("Iris.Domain.Tenancy.Customer", null)
                        .WithMany("Contexts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Iris.Domain.Applications.ApplicationDefinition", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Iris.Domain.Applications.ApplicationInstallation", b =>
                {
                    b.Navigation("Bindings");
                });

            modelBuilder.Entity("Iris.Domain.Applications.ApplicationVersion", b =>
                {
                    b.Navigation("ApplicationUnits");

                    b.Navigation("ConfigurationKeys");

                    b.Navigation("Dependencies");

                    b.Navigation("DependencyConstraints");

                    b.Navigation("InstallationProfiles");

                    b.Navigation("Placeholders");
                });

            modelBuilder.Entity("Iris.Domain.Infrastructure.ServerNode", b =>
                {
                    b.Navigation("Credentials");
                });

            modelBuilder.Entity("Iris.Domain.Tenancy.Customer", b =>
                {
                    b.Navigation("Contexts");
                });
#pragma warning restore 612, 618
        }
    }
}
