using System.Net;
using Iris.Application.Abstractions;
using Iris.Infrastructure.Integrations;

namespace Iris.Infrastructure.Tests.Integrations;

public sealed class AzureDevOpsConnectorTests
{
    private sealed class StubHandler(Func<HttpRequestMessage, HttpResponseMessage> respond) : HttpMessageHandler
    {
        public List<(string Method, string Path, string Query, string? AuthScheme, string? Body)> Calls { get; } = [];

        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            var body = request.Content?.ReadAsStringAsync(cancellationToken).GetAwaiter().GetResult();
            Calls.Add((request.Method.Method, request.RequestUri!.AbsolutePath, request.RequestUri.Query, request.Headers.Authorization?.Scheme, body));
            return Task.FromResult(respond(request));
        }
    }

    private static AzureDevOpsOptions Options() => new()
    {
        Endpoint = "https://dev.azure.com/algorab-devops",
        Token = "pat-value",
    };

    [Fact]
    public async Task GetFileContent_requests_the_expected_url_with_basic_auth_and_returns_raw_text()
    {
        var handler = new StubHandler(_ => new HttpResponseMessage(HttpStatusCode.OK) { Content = new StringContent("awx_context_blueprints: []") });
        using var connector = new AzureDevOpsConnector(Options(), handler);

        var content = await connector.GetFileContentAsync(
            "Refactoring_ops_flow", "awx", "master", "automation/manifests/awx_context_blueprints.yml");

        Assert.Equal("awx_context_blueprints: []", content);
        var call = Assert.Single(handler.Calls);
        Assert.Equal("GET", call.Method);
        Assert.Equal("/algorab-devops/Refactoring_ops_flow/_apis/git/repositories/awx/items", call.Path);
        Assert.Contains("versionDescriptor.version=master", call.Query);
        Assert.Equal("Basic", call.AuthScheme);
    }

    [Fact]
    public async Task GetFileContent_returns_null_on_404()
    {
        var handler = new StubHandler(_ => new HttpResponseMessage(HttpStatusCode.NotFound));
        using var connector = new AzureDevOpsConnector(Options(), handler);

        var content = await connector.GetFileContentAsync("Refactoring_ops_flow", "awx", "master", "missing.yml");

        Assert.Null(content);
    }

    [Fact]
    public async Task GetFileContent_throws_on_other_error_statuses()
    {
        var handler = new StubHandler(_ => new HttpResponseMessage(HttpStatusCode.Forbidden) { Content = new StringContent("no access") });
        using var connector = new AzureDevOpsConnector(Options(), handler);

        await Assert.ThrowsAsync<HttpRequestException>(() =>
            connector.GetFileContentAsync("Refactoring_ops_flow", "awx", "master", "secret.yml"));
    }

    private static AzureDevOpsChangeProposal Proposal() => new(
        Project: "Refactoring_ops_flow",
        Repository: "awx",
        BaseBranch: "master",
        NewBranchName: "iris/ansible-scaffold/foo-1.0.0-20260101000000",
        CommitMessage: "Iris: Ansible scaffold for foo v1.0.0",
        PrTitle: "Ansible scaffold for foo v1.0.0",
        PrDescription: "Auto-generated by Iris.",
        Files: new Dictionary<string, string>
        {
            ["roles/foo/tasks/main.yml"] = "---\n# tasks",
            ["playbooks/applications/foo.yml"] = "---\n# playbook",
        });

    private static StubHandler ProposeHandler(HttpStatusCode itemsStatus = HttpStatusCode.NotFound) =>
        new(request =>
        {
            var path = request.RequestUri!.AbsolutePath;
            if (path.EndsWith("/refs", StringComparison.Ordinal))
            {
                return new HttpResponseMessage(HttpStatusCode.OK)
                {
                    Content = new StringContent("""{"value":[{"objectId":"base-sha-123"}]}"""),
                };
            }

            if (path.EndsWith("/items", StringComparison.Ordinal))
            {
                return new HttpResponseMessage(itemsStatus);
            }

            if (path.EndsWith("/pushes", StringComparison.Ordinal))
            {
                return new HttpResponseMessage(HttpStatusCode.OK) { Content = new StringContent("{}") };
            }

            if (path.EndsWith("/pullrequests", StringComparison.Ordinal))
            {
                return new HttpResponseMessage(HttpStatusCode.OK)
                {
                    Content = new StringContent("""{"pullRequestId":42}"""),
                };
            }

            return new HttpResponseMessage(HttpStatusCode.NotFound);
        });

    [Fact]
    public async Task ProposeChange_creates_a_branch_off_the_base_commit_commits_every_file_and_opens_a_pr()
    {
        var handler = ProposeHandler();
        using var connector = new AzureDevOpsConnector(Options(), handler);

        var result = await connector.ProposeChangeAsync(Proposal());

        Assert.Equal(42, result.PullRequestId);
        Assert.Contains("/pullrequest/42", result.Url);

        var push = handler.Calls.Single(c => c.Path.EndsWith("/pushes", StringComparison.Ordinal));
        Assert.Equal("POST", push.Method);
        Assert.Contains("\"oldObjectId\":\"base-sha-123\"", push.Body);
        Assert.Contains("refs/heads/iris/ansible-scaffold/foo-1.0.0-20260101000000", push.Body);
        Assert.Contains("\"changeType\":\"add\"", push.Body); // items lookup returned 404 for both files
        Assert.Contains("/roles/foo/tasks/main.yml", push.Body);
        Assert.Contains("/playbooks/applications/foo.yml", push.Body);

        var pr = handler.Calls.Single(c => c.Path.EndsWith("/pullrequests", StringComparison.Ordinal));
        Assert.Contains("refs/heads/master", pr.Body);
        Assert.Contains("refs/heads/iris/ansible-scaffold/foo-1.0.0-20260101000000", pr.Body);
    }

    [Fact]
    public async Task ProposeChange_uses_edit_for_files_that_already_exist_at_the_base_branch_tip()
    {
        var handler = ProposeHandler(itemsStatus: HttpStatusCode.OK);
        using var connector = new AzureDevOpsConnector(Options(), handler);

        await connector.ProposeChangeAsync(Proposal());

        var push = handler.Calls.Single(c => c.Path.EndsWith("/pushes", StringComparison.Ordinal));
        Assert.Contains("\"changeType\":\"edit\"", push.Body);
        Assert.DoesNotContain("\"changeType\":\"add\"", push.Body);
    }

    [Fact]
    public async Task ProposeChange_throws_when_the_base_branch_does_not_exist()
    {
        var handler = new StubHandler(request => request.RequestUri!.AbsolutePath.EndsWith("/refs", StringComparison.Ordinal)
            ? new HttpResponseMessage(HttpStatusCode.OK) { Content = new StringContent("""{"value":[]}""") }
            : new HttpResponseMessage(HttpStatusCode.NotFound));
        using var connector = new AzureDevOpsConnector(Options(), handler);

        await Assert.ThrowsAsync<InvalidOperationException>(() => connector.ProposeChangeAsync(Proposal()));
    }
}
