using Iris.Application.Abstractions;
using Iris.Application.Common;
using Iris.Contracts.Applications;

namespace Iris.Application.Applications;

/// <summary>Command for <c>POST /applications/{applicationId}/versions/{versionId}/ansible-scaffold/propose</c>.
/// Generates the same scaffold <see cref="GenerateApplicationAnsibleScaffoldHandler"/> returns for
/// download, remaps its paths to the AWX automation repo's own conventions, and proposes it there
/// as a Pull Request — Iris never pushes to the repo's base branch directly; a human reviews and
/// merges.</summary>
public sealed record ProposeAnsibleScaffoldToAwxRepoCommand(Guid ApplicationId, Guid VersionId);

public sealed class ProposeAnsibleScaffoldToAwxRepoHandler(
    GenerateApplicationAnsibleScaffoldHandler scaffoldGenerator,
    IApplicationRepository applications,
    IIntegrationSettingsRepository settingsRepository,
    IAzureDevOpsRepositoryWriter writer,
    IClock clock)
{
    public async Task<ProposeAnsibleScaffoldResponse> HandleAsync(
        ProposeAnsibleScaffoldToAwxRepoCommand command,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(command);

        var application = await applications.GetAsync(command.ApplicationId, cancellationToken).ConfigureAwait(false)
            ?? throw new NotFoundException("Application", command.ApplicationId);
        var settings = await settingsRepository.GetAsync(cancellationToken).ConfigureAwait(false);

        // A per-application override (App settings) wins field-by-field; anything left unset
        // falls back to the global Azure DevOps "AWX automation repo" settings.
        var project = application.AwxRepositoryProject ?? settings?.AzureDevOpsProject;
        var repository = application.AwxRepositoryName ?? settings?.AzureDevOpsRepository;
        if (string.IsNullOrWhiteSpace(project) || string.IsNullOrWhiteSpace(repository))
        {
            throw new ValidationException(
                "Configure the AWX automation repo's project/repository — either on this application, or globally in " +
                "System settings (Configure Azure DevOps) — before proposing a scaffold.");
        }

        var scaffold = await scaffoldGenerator
            .HandleAsync(new GenerateApplicationAnsibleScaffoldQuery(command.ApplicationId, command.VersionId), cancellationToken)
            .ConfigureAwait(false);

        var branch = application.AwxRepositoryBranch
            ?? (string.IsNullOrWhiteSpace(settings?.AzureDevOpsBranch) ? "master" : settings.AzureDevOpsBranch);
        var newBranchName = $"iris/ansible-scaffold/{scaffold.ApplicationSlug}-{scaffold.Version}-{clock.UtcNow:yyyyMMddHHmmss}";
        var files = scaffold.Files.ToDictionary(file => RemapPath(scaffold.ApplicationSlug, file.RelativePath), file => file.Content);

        var proposal = new AzureDevOpsChangeProposal(
            project,
            repository,
            branch,
            newBranchName,
            $"Iris: Ansible scaffold for {scaffold.ApplicationSlug} v{scaffold.Version}",
            $"Ansible scaffold for {scaffold.ApplicationSlug} v{scaffold.Version}",
            $"Auto-generated by Iris from the '{scaffold.ApplicationSlug}' v{scaffold.Version} manifest on {scaffold.GeneratedAtUtc:u}. " +
            "Starting point only — review and edit before merging; Iris will not overwrite these files once they're committed here.",
            files);

        var result = await writer.ProposeChangeAsync(proposal, cancellationToken).ConfigureAwait(false);
        return new ProposeAnsibleScaffoldResponse(result.PullRequestId, result.Url);
    }

    /// <summary>Maps the generic scaffold layout (<c>Iris.Application.Applications.AnsibleScaffoldGenerator</c>'s
    /// output, meant for a standalone zip) onto the awx repo's own conventions:
    /// <c>roles/&lt;slug&gt;/...</c> already matches as-is; a top-level <c>playbooks/&lt;slug&gt;.yml</c>
    /// moves under <c>playbooks/applications/</c> (matching the repo's existing folder); the bare
    /// <c>README.md</c> is tucked inside the role folder instead of landing at the repo root, where
    /// it would silently propose overwriting the awx repo's own top-level README.</summary>
    private static string RemapPath(string slug, string relativePath) => relativePath switch
    {
        "README.md" => $"roles/{slug}/README.md",
        _ when relativePath.StartsWith("playbooks/", StringComparison.Ordinal) =>
            $"playbooks/applications/{relativePath["playbooks/".Length..]}",
        _ => relativePath,
    };
}
