<#
.SYNOPSIS
    Reports which .knowledge/ concept files reference source paths that have
    changed since the concept was last verified.

.DESCRIPTION
    For each concept file's `source.commit` and `source.paths`, runs
    `git log <commit>..HEAD -- <path>` for every path. Any path with commits in
    that range is "drifted": the code moved on after the concept was written,
    so the concept's claims should be re-verified before being trusted.

    This is deliberately advisory only (exit code is always 0): the Phase 1
    plan lists "drift rilevato" as something to log/observe, not an automatic
    hard failure, since no drift-ratio threshold has been agreed yet (inventing
    one now would be exactly the kind of unverified assumption this layer is
    supposed to avoid). Wire in a threshold once there's enough real drift data
    to pick a non-arbitrary number.

    Same PoC-grade caveat as Validate-Knowledge.ps1: frontmatter is read with
    regex, not a real YAML parser.

.OUTPUTS
    Writes .knowledge/drift-report.md. Always exits 0.
#>

$ErrorActionPreference = 'Stop'

$knowledgeRoot = Split-Path -Parent $PSScriptRoot
$repoRoot = Split-Path -Parent $knowledgeRoot

Push-Location $repoRoot
try {
    $headCommit = (git rev-parse HEAD | Out-String).Trim()
} finally {
    Pop-Location
}

$conceptFiles = Get-ChildItem -Path $knowledgeRoot -Recurse -Filter '*.md' |
    Where-Object { $_.FullName -notmatch '\\(index|log|validation-report|benchmark-report|MAINTENANCE)\.md$' }

$drifted = New-Object System.Collections.Generic.List[string]
$clean = New-Object System.Collections.Generic.List[string]
$unverifiable = New-Object System.Collections.Generic.List[string]

foreach ($file in $conceptFiles) {
    $rel = $file.FullName.Substring($repoRoot.Length + 1).Replace('\', '/')
    $text = Get-Content -Raw -Path $file.FullName

    if ($text -notmatch '(?s)^---\r?\n(.*?)\r?\n---\r?\n') { continue }
    $frontmatter = $Matches[1]

    if ($frontmatter -notmatch '(?s)source:\s*\r?\n((?:[ \t]+.*\r?\n?)+)') {
        $unverifiable.Add("$rel : no source: block found") | Out-Null
        continue
    }
    $sourceBlock = $Matches[1]

    if ($sourceBlock -notmatch 'commit\s*:\s*(\S+)') {
        $unverifiable.Add("$rel : source.commit missing") | Out-Null
        continue
    }
    $sourceCommit = $Matches[1].Trim()

    if ($sourceBlock -notmatch '(?s)paths\s*:\s*\r?\n((?:\s*-\s+.*\r?\n?)+)') {
        $unverifiable.Add("$rel : source.paths missing or empty") | Out-Null
        continue
    }
    $pathsBlock = $Matches[1]
    $pathMatches = [regex]::Matches($pathsBlock, '(?m)^\s*-\s+(\S+)\s*$')

    $changedPaths = New-Object System.Collections.Generic.List[string]
    foreach ($pm in $pathMatches) {
        $path = $pm.Groups[1].Value.Trim()

        Push-Location $repoRoot
        try {
            $range = "$sourceCommit..$headCommit"
            $log = git log --format=%H $range -- $path
        } catch {
            $log = $null
        } finally {
            Pop-Location
        }

        if ($LASTEXITCODE -ne 0) {
            $unverifiable.Add("$rel : could not run 'git log $sourceCommit..HEAD -- $path' (commit may not exist locally, e.g. a shallow clone)") | Out-Null
            continue
        }

        if (-not [string]::IsNullOrWhiteSpace($log)) {
            $changedPaths.Add($path) | Out-Null
        }
    }

    if ($changedPaths.Count -gt 0) {
        $drifted.Add("$rel (source.commit $sourceCommit) - changed paths: $($changedPaths -join ', ')") | Out-Null
    } else {
        $clean.Add("$rel (source.commit $sourceCommit, unchanged through $headCommit)") | Out-Null
    }
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('# Knowledge layer - drift report') | Out-Null
$lines.Add('') | Out-Null
$lines.Add('_Generated by `.knowledge/tools/Detect-Drift.ps1`. Advisory only - a concept') | Out-Null
$lines.Add('listed as drifted is not necessarily wrong, it is unverified since one of its') | Out-Null
$lines.Add('source paths changed. Re-check it before trusting it for anything consequential._') | Out-Null
$lines.Add('') | Out-Null
$lines.Add("HEAD at generation time: $headCommit") | Out-Null
$lines.Add("Generated at (UTC): $((Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ'))") | Out-Null
$lines.Add('') | Out-Null
$lines.Add("## Drifted ($($drifted.Count))") | Out-Null
$lines.Add('') | Out-Null
if ($drifted.Count -eq 0) { $lines.Add('None.') | Out-Null }
else { foreach ($d in $drifted) { $lines.Add("- $d") | Out-Null } }
$lines.Add('') | Out-Null
$lines.Add("## Clean ($($clean.Count))") | Out-Null
$lines.Add('') | Out-Null
if ($clean.Count -eq 0) { $lines.Add('None.') | Out-Null }
else { foreach ($c in $clean) { $lines.Add("- $c") | Out-Null } }
$lines.Add('') | Out-Null
$lines.Add("## Could not verify ($($unverifiable.Count))") | Out-Null
$lines.Add('') | Out-Null
if ($unverifiable.Count -eq 0) { $lines.Add('None.') | Out-Null }
else { foreach ($u in $unverifiable) { $lines.Add("- $u") | Out-Null } }

$reportPath = Join-Path $knowledgeRoot 'drift-report.md'
Set-Content -Path $reportPath -Value ($lines -join "`n") -Encoding utf8

Write-Output "Drift check: $($drifted.Count) drifted, $($clean.Count) clean, $($unverifiable.Count) unverifiable."
exit 0
