<#
.SYNOPSIS
    PoC-grade validator for the .knowledge/ concept files.

.DESCRIPTION
    This is deliberately NOT a real YAML parser (PowerShell 5.1 ships no
    ConvertFrom-Yaml, and this environment has no package feed access to add
    one). It uses regex against the frontmatter block, which is good enough to
    catch the concrete failure modes the Phase-1 spec asked for: missing
    required fields, dangling relation targets, dangling evidence paths, and
    unknown enum values. It will NOT catch structurally invalid YAML.

    Phase 4 (Hardening) should replace this with a real parser - either a
    small dotnet tool using YamlDotNet + Markdig (idiomatic for this repo,
    which is already .NET), or a CI step in Python with PyYAML. Do not let
    this script's heuristics become load-bearing beyond the PoC.

.OUTPUTS
    Writes .knowledge/validation-report.md and exits 1 if any blocking error
    was found (repo root is two levels up from this script).
#>

$ErrorActionPreference = 'Stop'

$knowledgeRoot = Split-Path -Parent $PSScriptRoot
$repoRoot = Split-Path -Parent $knowledgeRoot

$requiredTopLevel = @('type', 'name', 'title', 'description', 'status')
$allowedStatus = @('active', 'draft', 'deprecated', 'accepted', 'superseded')
$allowedConfidence = @('verified', 'inferred', 'curated', 'stale', 'conflicting')

# Concept files only - index.md/log.md are meta pages, validation-report.md is
# this script's own output. None of the three carry frontmatter by design.
$conceptFiles = Get-ChildItem -Path $knowledgeRoot -Recurse -Filter '*.md' |
    Where-Object { $_.FullName -notmatch '\\(index|log|validation-report)\.md$' }

$errors = New-Object System.Collections.Generic.List[string]
$warnings = New-Object System.Collections.Generic.List[string]
$checked = New-Object System.Collections.Generic.List[string]

foreach ($file in $conceptFiles) {
    $rel = $file.FullName.Substring($repoRoot.Length + 1).Replace('\', '/')
    $checked.Add($rel) | Out-Null
    $text = Get-Content -Raw -Path $file.FullName

    if ($text -notmatch '(?s)^---\r?\n(.*?)\r?\n---\r?\n') {
        $errors.Add("$rel : no frontmatter block found") | Out-Null
        continue
    }
    $frontmatter = $Matches[1]

    foreach ($key in $requiredTopLevel) {
        if ($frontmatter -notmatch "(?m)^$key\s*:") {
            $errors.Add("$rel : missing required field '$key'") | Out-Null
        }
    }

    if ($frontmatter -match '(?m)^status\s*:\s*(\S+)') {
        $status = $Matches[1].Trim()
        if ($allowedStatus -notcontains $status) {
            $warnings.Add("$rel : unrecognised status '$status'") | Out-Null
        }
    }

    if ($frontmatter -match 'confidence\s*:\s*(\S+)') {
        $confidence = $Matches[1].Trim()
        if ($allowedConfidence -notcontains $confidence) {
            $warnings.Add("$rel : unrecognised provenance.confidence '$confidence'") | Out-Null
        }
    }

    if ($frontmatter -notmatch 'commit\s*:\s*\S+') {
        $warnings.Add("$rel : source.commit missing - cannot judge staleness") | Out-Null
    }

    # relation targets: lines like "    target: ../domains/applications.md"
    $targetMatches = [regex]::Matches($frontmatter, '(?m)^\s*target:\s*(\S+)\s*$')
    foreach ($m in $targetMatches) {
        $target = $m.Groups[1].Value.Trim()
        if ($target -eq 'none' -or [string]::IsNullOrWhiteSpace($target)) { continue }
        $resolved = Join-Path $file.DirectoryName $target
        $resolved = [System.IO.Path]::GetFullPath($resolved)
        if (-not (Test-Path -LiteralPath $resolved)) {
            $errors.Add("$rel : relation target does not exist -> $target") | Out-Null
        }
    }

    # evidence entries: list items "      - src/Foo/Bar.cs" (strip #line anchors)
    $evidenceMatches = [regex]::Matches($frontmatter, '(?m)^\s*-\s+([A-Za-z0-9_./-]+\.[A-Za-z0-9]+)(#\S+)?\s*$')
    foreach ($m in $evidenceMatches) {
        $evidencePath = $m.Groups[1].Value.Trim()
        $resolved = Join-Path $repoRoot $evidencePath
        if (-not (Test-Path -LiteralPath $resolved)) {
            $warnings.Add("$rel : evidence path not found in repo -> $evidencePath (may be a relation target picked up by the same regex - verify by hand)") | Out-Null
        }
    }
}

$reportLines = New-Object System.Collections.Generic.List[string]
$reportLines.Add('# Knowledge layer - validation report') | Out-Null
$reportLines.Add('') | Out-Null
$reportLines.Add('_Generated by `.knowledge/tools/Validate-Knowledge.ps1`. This is a PoC-grade,') | Out-Null
$reportLines.Add('regex-based check, not a full YAML/schema validator - see the script header._') | Out-Null
$reportLines.Add('') | Out-Null
$reportLines.Add("Generated at (UTC): $((Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ'))") | Out-Null
$reportLines.Add("Files checked: $($checked.Count)") | Out-Null
$reportLines.Add('') | Out-Null
$reportLines.Add('## Blocking errors') | Out-Null
$reportLines.Add('') | Out-Null
if ($errors.Count -eq 0) {
    $reportLines.Add('None.') | Out-Null
} else {
    foreach ($e in $errors) { $reportLines.Add("- $e") | Out-Null }
}
$reportLines.Add('') | Out-Null
$reportLines.Add('## Warnings (non-blocking)') | Out-Null
$reportLines.Add('') | Out-Null
if ($warnings.Count -eq 0) {
    $reportLines.Add('None.') | Out-Null
} else {
    foreach ($w in $warnings) { $reportLines.Add("- $w") | Out-Null }
}
$reportLines.Add('') | Out-Null
$reportLines.Add('## Files checked') | Out-Null
$reportLines.Add('') | Out-Null
foreach ($c in $checked) { $reportLines.Add("- $c") | Out-Null }

$reportPath = Join-Path $knowledgeRoot 'validation-report.md'
Set-Content -Path $reportPath -Value ($reportLines -join "`n") -Encoding utf8

Write-Output "Checked $($checked.Count) concept files: $($errors.Count) error(s), $($warnings.Count) warning(s)."
if ($errors.Count -gt 0) {
    exit 1
}
exit 0
